### PR TITLE
Force Update and Post Doubt Changes

### PR DESCRIPTION
**Pull request by Aditya13s**

### CODE REVIEW

**Comment by sidsharma2002** [comment]
You also need to add a default_remote_config.xml file to tell remote config the default values. https://firebase.google.com/docs/remote-config/get-started?&platform=android#set_in_app_default_parameter_values

**Comment by sidsharma2002** [comment]
add analytics event here with name "feedback_btn_click", send common properties in params and nothing else.

**Comment by sidsharma2002** [comment]
get RemoteConfig from DI i.e AppComp, we'll get that from app comp throughout the app so that we don't need to set config settings every time. Set fetch interval to every 2 mins = 120 seconds.

**Comment by Aditya13s** [comment]
@sidsharma2002 Please review the changes

**Comment by sidsharma2002** [comment]
Great! merging it now!

**Pull request merged**
